### PR TITLE
Add es5 output compiled with babel-preset-env

### PR DESCRIPTION
**Pull request by GeKorm**
Addresses #19  
I didn't add a minified version as it's standard practice (and default webpack behavior) to minify the entire bundle. Let me know if we need this.

I also added a "using with webpack" example in the readme, in case you'd like to include instructions.

As for testing, I manually ran the tests by pointing to lib/tiny-lru.es5.js and they passed. Do you think it's worth changing it to run 2 sets?

Thank you

### CODE REVIEW

**Comment by avoidwork** [comment]
@GeKorm the module webpacks just fine for me. I don't see why this is needed.

# sample script
```
const lru = require('tiny-lru'),
	cache = lru(1e5, 3e5);

cache.set('abc', true);

module.exports = cache;
```

# webpack.config.js
```
const path = require('path');

module.exports = {
	entry: './index.js',
	output: {
		path: path.resolve(__dirname, 'dist'),
		filename: 'bundle.js'
	},
	stats: {
		colors: true
	},
	devtool: 'source-map'
};
```

# webpack output
```
!function(t){var e={};function i(s){if(e[s])return e[s].exports;var n=e[s]={i:s,l:!1,exports:{}};return t[s].call(n.exports,n,n.exports,i),n.l=!0,n.exports}i.m=t,i.c=e,i.d=function(t,e,s){i.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:s})},i.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},i.t=function(t,e){if(1&e&&(t=i(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var s=Object.create(null);if(i.r(s),Object.defineProperty(s,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var n in t)i.d(s,n,function(e){return t[e]}.bind(null,n));return s},i.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return i.d(e,"a",e),e},i.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},i.p="",i(i.s=0)}([function(t,e,i){const s=i(1)(1e5,3e5);s.set("abc",!0),t.exports=s},function(t,e,i){"use strict";(function(e){
/**
 * Tiny LRU cache for Client or Server
 *
 * @author Jason Mulligan <jason.mulligan@avoidwork.com>
 * @copyright 2019
 * @license BSD-3-Clause
 * @version 6.0.0
 */
!function(e){class i{constructor(t=0,e=0){this.first=null,this.items={},this.last=null,this.max=t,this.size=0,this.ttl=e}has(t){return t in this.items}clear(){return this.first=null,this.items={},this.last=null,this.size=0,this}delete(t){if(this.has(t)){const e=this.items[t];delete this.items[t],this.size--,null!==e.prev&&(e.prev.next=e.next),null!==e.next&&(e.next.prev=e.prev),this.first===e&&(this.first=e.next),this.last===e&&(this.last=e.prev)}return this}evict(){const t=this.first;return delete this.items[t.key],this.first=t.next,this.first.prev=null,this.size--,this}get(t){let e;if(this.has(t)){const i=this.items[t];this.ttl>0&&i.expiry<=(new Date).getTime()?this.delete(t):(e=i.value,this.set(t,e,!0))}return e}keys(){return Object.keys(this.items)}set(t,e,i=!1){let s;if(i||this.has(t)){if((s=this.items[t]).value=e,this.last!==s){const t=this.last,e=s.next,i=s.prev;this.first===s&&(this.first=s.next),s.next=null,s.prev=this.last,t.next=s,null!==i&&(i.next=e),null!==e&&(e.prev=i)}}else this.max>0&&this.size===this.max&&this.evict(),s=this.items[t]={expiry:this.ttl>0?(new Date).getTime()+this.ttl:this.ttl,key:t,prev:this.last,next:null,value:e},1==++this.size?this.first=s:this.last.next=s;return this.last=s,this}}t.exports=function(t=1e3,e=0){if(isNaN(t)||t<0)throw new TypeError("Invalid max value");if(isNaN(e)||e<0)throw new TypeError("Invalid ttl value");return new i(t,e)}}("undefined"!=typeof window&&window)}).call(this,i(2))},function(t,e){var i;i=function(){return this}();try{i=i||new Function("return this")()}catch(t){"object"==typeof window&&(i=window)}t.exports=i}]);
//# sourceMappingURL=bundle.js.map
```

**Comment by GeKorm** [comment]
The above fails in two common scenarios:

- Needing to transpile to es5, which a ton of browser-facing webpack apps do with babel. It requires a workaround in the babel loader configuration (see https://github.com/webpack/webpack/issues/2031). You'll notice your output above includes es6 code.
- Even with that workaround, UglifyJs fails as it can't handle es6 code. It's possible a config workaround or less ideal chunking configuration exists to address this, but we probably shouldn't ask that from users.

**Comment by avoidwork** [comment]
Ok, but your original issue was...

```
Hi. The last version that works with modules import lru from 'tiny-lru' when bundling with webpack is 1.6.4
As far as I can tell the compilation method/target has changed since version 2.0.0; I haven't found a way to import tiny-lru as a module since then.

Thank you
```

Which  is specific for the `import` keyword, and the only difference between the versions at that time was removing the transpile; the module has always webpacked.

The minification above is just an example, i could use one of the other libs that is fronting an es module and it'd be ok, like I do with the module already.

Is your core concern that transpile was dropped, or is it webpack? If it's just the transpile I don't think that should live in this project, as it's an antiquated issue that you can manage in your own fork.

**Comment by GeKorm** [comment]
This PR also allows the use of `import`, but that is a side-effect. The original issue reported the symptom, which upon further investigation turned out to be caused by lack of es5 support.

[babel-preset-env](https://www.npmjs.com/package/@babel/preset-env) isn't showing signs of slowing. Most modules that target browsers even nowadays provide a transpiled version.

From experience in projects I've worked on, I can't drop es5 support in any public-facing browser apps as I'd be dropping more than 10% of our users. I've never had a client that would accept this. 

Your project seems to be used mostly by node packages, so it's totally understandable if you don't want the additional build step. If you decide to include it, feel free to send me a message any time you want to update babel or anything like that :)

**Comment by GeKorm** [comment]
Hey @avoidwork, in case you're still making up your mind about this, here is some prior discussion. 

https://twitter.com/jamiebuilds/status/1080840492525350912
https://github.com/facebook/create-react-app/issues?q=is%3Aissue+Failed+to+minify+the+code+is%3Aclosed (recently solved in v2 of react-scripts)
https://github.com/zeit/next.js/issues/706 
https://github.com/rsms/js-lru/issues/30

> Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

Again, I agree with you on this issue, except I think it's still a bit too early to ditch es5 completely. Also, I have no problem maintaining a fork.

**Comment by avoidwork** [comment]
Could you provide a sample script/config that I can look at to understand the issue more.

**Comment by avoidwork** [comment]
nm, it's really not that important to me... merging!

**Comment by avoidwork** [comment]
@GeKorm published 6.0.1

**Comment by avoidwork** [comment]
thanks for the example!

**Pull request merged**
