### PR TITLE
Always reset TTL for explicit sets, but never for LRU bumps

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by avoidwork** [comment]
This is not how a cache is expected behave by default, which is why it's best done with the optional third param. It's off by default because that's what people expect.

**Comment by kibertoad** [comment]
@avoidwork This one I would have to challenge a bit.

There are two distinctive cases when SET operation is invoked now:

1) When user is setting something to a new value (indicating the new up-to-date value in the system);
2) When user is getting something (simply indicating that something somewhere needs the data).

First one should always bump the TTL, because explicit SET operation implies that this is the absolutely freshest data right now.
Second one should never bump the TTL, because reading the data says nothing about how fresh or stale the data is it, it should only move the data up in the LRU list, but that's it.

Currently the two are conflated, but they shouldn't be. Config param was a mistake on my part, I wasn't aware that we always perform SET on GET. Existence of param is more confusing and dangerous than helpful, instead, TTL reset should be based on whether or not this is a part of a GET operation.

**Comment by avoidwork** [comment]
It's meant to be DRY, so if it's confusing it's because people aren't reading the code before trying to change it.

It's been that was since the initial commit. The ops would repeat so there's no reason for it not be sequential.

**Comment by avoidwork** [comment]
The creeping TTL was introduced with 7.x.x and removed with 8.x.x after real world issues from products started rolling in because people sometimes just increased versions without understanding that the way it worked just flipped entirely on them.

The way it's coded now supports all types of runs afaik without overlap / unexpected behavior; you have to opt in with a single boolean.

**Comment by kibertoad** [comment]
@avoidwork Documentation needs to be updated to clarify that it affects both GET and SET operations, then, as this is not what most users would expect.

**Comment by avoidwork** [comment]
You're welcome to make the PR; I disagree that it's required. It's >10yr and the first time I've seen someone raise a concern a method calls another method.

**Comment by avoidwork** [comment]
Regarding "Currently the two are conflated, but they shouldn't be."; I disagree. I haven't combined 2+ ideas into 1, I've sequentially called 2 methods that do not have repeating ops because they are required, and they were coded in such a way as to avoid deopts (roughly 5yr ago).

I don't grok what you're perceiving as a flaw.

**Pull request closed without merging**
