### PR TITLE
Use Map for faster execution

### PR DESCRIPTION
**Pull request by kibertoad**
See https://github.com/kibertoad/nodejs-benchmark-tournament/blob/master/has-field/_results/results.md (for hits) and https://github.com/kibertoad/nodejs-benchmark-tournament/blob/master/has-field-miss/_results/results.md (for misses)

For ~100 entries Map is generally the fastest way of checking whether element is present.
It is also faster than direct field access for data retrieval.

This is also consistent with https://gist.github.com/Chunlin-Li/2606bd813df88eaeee2d?permalink_comment_id=3089685#gistcomment-3089685 claiming that objects are slower for key access than maps.

### CODE REVIEW

**Comment by avoidwork** [comment]
To consider this I'd need to see the telemetry of a long running process, a few hours or days, with at least 10MiB shifting through it.

100 entries is not realistic for real world usage.

**Comment by avoidwork** [comment]
It'd be nice if Maps are fast enough these days, as the only deopt in the code happens from shape mutation over time on the items.

**Comment by kibertoad** [comment]
Sure, I'll adjust the benchmark to operate on larger dataset with more iterations.

**Comment by avoidwork** [comment]
Removing the `has()` produces this timing:

```
1.3626,1.3146,1.341
1.1781,1.194,1.5818
1.4245,1.5818,1.4397
0.3243,0.2453,0.2287
0.7747,0.8867,0.8103
```

Which is a little closer to the speed of the current Object.

**Comment by kibertoad** [comment]
Would be interesting to only keep P95 and see which one performs well more consistently.

**Comment by kibertoad** [comment]
Simple example: https://github.com/kibertoad/photofinish/blob/master/lib/internal/mathUtils.ts

**Comment by avoidwork** [comment]
Oh, i'm not after a better benchmark ... I want real world telemetry and the ability to audit the data shape going in, schema definition would be good enough tbh.

I have a platform that's been live since '18 using this lib in 3 tiers holding MiB to GiB as various jobs are executed.

We need to see how it performs with sythentic data.

**Comment by kibertoad** [comment]
> I want real world telemetry and the ability to audit the data shape going in, schema definition would be good enough tbh.

How can this be done without change being released?

**Comment by avoidwork** [comment]
Run an experiement instead of a benchmark ;)

**Comment by kibertoad** [comment]
Sure, I'll try to cook something up.

**Comment by avoidwork** [comment]
Maybe the numbers i provided is enough... it looks like it's pretty close to equal with small things with that test which was just aiming to show evicts don't get slower; I would assume the Map would perform better in IRL with larger data sets.

**Comment by avoidwork** [comment]
Could you put this back to 'ready', I'll produce so more data... I think we merge today/tomorrow, depending on time.

**Comment by avoidwork** [comment]
I think you missed the `size` getter in your PR: https://github.com/avoidwork/tiny-lru/blob/mapAgain/src/lru.js#L153-L155

**Comment by avoidwork** [comment]
Could you move it so it's in the alphabetical spot please.

**Comment by kibertoad** [comment]
sure!

**Comment by kibertoad** [comment]
@avoidwork so did you get a chance to test it?

**Comment by avoidwork** [comment]
@kibertoad sorta, i had been using maps to hold gigs of data that shifted every 30min for another part of a work system, which covered all of my concerns - that code had been in prod for years and it grew from a few hundred MiB to around 9 GiB before i had changed teams.

**Comment by avoidwork** [comment]
This is 10.3.0 🚀

**Pull request merged**
