### PR TITLE
fix: improve esm-cjs interoperability

### LINKED ISSUE #110: SyntaxError: Unexpected token 'export'
Using  { node: 'v16.16.0', npm: '9.6.4' } 
I get  the below error
```
/node_modules/tiny-lru/dist/tiny-lru.js:178
   }export{lru};
    ^^^^^^
   SyntaxError: Unexpected token 'export'
```

Extra: this package is required by `maxmind`  which is a dependency of `@maxmind/geoip2-node`

### PR DESCRIPTION
**Pull request by castarco**
Fixes #110 .

### CODE REVIEW

**Comment by avoidwork** [comment]
Hi, based on the package.json docs that's not a fix. If your tooling is choosing the wrong version the issue in the tooling.

**Comment by avoidwork** [comment]
#110 is fixed by upgrading jest to a version that's compliant with node + npm, not by introducing unsupported keys.

if you're "fix" is not found on this page, it's not a fix: https://docs.npmjs.com/cli/v10/configuring-npm/package-json

**Comment by castarco** [comment]
It is a fix, as it provides backwards compatibility. It's not just about shitty tools. The `exports` section hasn't been there forever, there was a time when that was not a thing.

On top of that, not specifying the whole file path for the `main` entry is plain wrong.

**Comment by avoidwork** [comment]
for total clarity, the issue you're running into due to non-compliant tooling is addressed by putting the extension on the value of "main", but it's intentionally absent. more details can be found at https://nodejs.org/api/packages.html

**Comment by castarco** [comment]
I'm already very familiar with all the documentation that you pointed out. It does not justify your position, but in any case it's your project and your rules, so I'll leave it there.

**Comment by avoidwork** [comment]
What benefit do we get as a community by supporting anti-patterns? if it's not in the node or npm docs, it's not "real" - temporary resolutions would/should be fixed to a point in time and removed when the real solution is presented.

as per node's docs:

Screenshot 2023-10-10 063016

Screenshot 2023-10-10 062823

**Comment by avoidwork** [comment]
Latest docs example has the extension, so I've set that with https://github.com/avoidwork/tiny-lru/commit/345cde554aacc763325904b41822ad95640c2875#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R20 which is the clear solution in the latest iteration of the docs; what I had referenced is now outdated.

**Pull request closed without merging**
